spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ex_intermediate
    username: postgres
    password: postgres
server:
  servlet:
    context-path: /ex-intermediate
logging:
  level:
    '[org.springframework.jdbc.core]': debug
    '[com.example.exintermediate]': debug
